# Site settings
title: Raphael Fabeni
name: Raphael Fabeni
email: rapha.fabeni@gmail.com
description: "A brazilian front-end developer who loves the web, electronic music and travels."
baseurl: "/"
url: "http://www.raphaelfabeni.com.br"
url_en: "http://www.raphaelfabeni.com.br/en"
exclude: ['node_modules', 'package.json', 'bin', 'README.md', 'script.bash', 'Gemfile.lock', 'Gemfile', 'start.bash', 'src']

# Build settings
markdown: kramdown
permalink: pretty
syntax_highlighter: rouge

source:      .
destination: ./_site
permalink:   /:categories/:title/
